version: '3'
services:
  books:
    build: .
    restart: on-failure
    ports:
      - "9080:8000"
    volumes:
      - .:/var/www/bookstore
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      DEBUG: 'True'
      ENV_TYPE: 'local'
    # required for pdb debugger - run `docker attach <containerid>`
    stdin_open: true
    tty: true

  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - database:/var/lib/postgresql

  redis:
    image: redis:alpine # AWS ElastiCache Redis will be used in deployed environments

volumes:
  database:
